---
swagger: "2.0"
info:
  description: "This is swagger Api documentation for notification service."
  version: "1.0.5"
  title: "Notification Service"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v1"
tags:
- name: "notification"
  description: "Everything about notification"
schemes:
- "https"
- "http"
components:
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT 
paths:
  /notification:
    post:
      tags:
      - "notification"
      summary: "Add a new notification"
      description: ""
      operationId: "addNotification"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "x-selected-tenant"
        in: "header"
        description: "ID of tenant"
        required: true
        type: "string"

      - in: "body"
        name: "body"
        description: "ID of notificataion assigne"
        required: true
        schema:
          $ref: "#/definitions/Notification"    
      responses:
        201:
          description: "Notification create successful"
      security:
      - bearerAuth: []  

  /notification/{assignId}:
    get:
      tags:
      - "notification"
      summary: "Add a new notification"
      description: ""
      operationId: "listNotification"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "assignId"
        in: "path"
        description: "Notification list with assignId"
        required: true
        type: "string"
      responses:
        200:
          description: "Notification list successful"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  
  /notification/{notificationId}/{userId}:
    put:
      tags:
      - "notification"
      summary: "Update for read a notification"
      description: ""
      operationId: "readNotification"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "notificationId"
        in: "path"
        description: "Notification Id"
        required: true
        type: "string"

      - name: "userId"
        in: "path"
        description: "User Id"
        required: true
        type: "string"
        
      responses:
        200:
          description: "Update for read notification successful"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"

  /notification/{notificationId}/{userId}/delete:
    put:
      tags:
      - "notification"
      summary: "Update for read a notification"
      description: ""
      operationId: "deleteNotification"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "notificationId"
        in: "path"
        description: "Notification Id"
        required: true
        type: "string"

      - name: "userId"
        in: "path"
        description: "User Id"
        required: true
        type: "string"
        
      responses:
        200:
          description: "Delete for read notification successful"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "https://petstore.swagger.io/oauth/authorize"
    flow: "implicit"
    scopes:
      read:pets: "read your pets"
      write:pets: "modify pets in your account"
definitions:
  Notification:
    type: "object"
    properties:
      assignId:
        type: "string"
      ownerId:
        type: "string"
      type:
        type: "string"
      body:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
